export const showcase = [
  {
    id: 1,
    img: '/images/sc/sc1.png',
    data_size: 's',
    title: 'Neon, from EngineeringUK',
    author: ['Clearleft'],
  },
  {
    id: 2,
    img: '/images/sc/sc2.png',
    data_size: 'l',
    title: 'Every Layout',
    author: ['Andy Bell'],
  },
  {
    id: 3,
    img: '/images/sc/sc3.png',
    data_size: 'l',
    title: 'HUSTLERSQUADGRAFFICKS',
    author: ['James Gilyead'],
  },
  {
    id: 4,
    img: '/images/sc/sc4.png',
    data_size: 's',
    title: 'Set Studio',
    author: ['Andy Bell, James Gilyead', 'Leanne Renard', 'Amy Hupe'],
  },
  {
    id: 5,
    img: '/images/sc/sc5.png',
    data_size: 's',
    title: 'Andy Budd',
    author: ['James Gilyead', 'Trys Mudford'],
  },
  {
    id: 6,
    img: '/images/sc/sc6.png',
    data_size: 'l',
    title: 'Malvern Panalytical',
    author: ['Clearleft'],
  },
  {
    id: 7,
    img: '/images/sc/sc7.png',
    data_size: 'l',
    title: 'Smoke and Fire Festival',
    author: ['Leon Harris'],
  },
  {
    id: 8,
    img: '/images/sc/sc8.png',
    data_size: 's',
    title: 'A Human Future',
    author: ['Andy Bell'],
  },
  {
    id: 9,
    img: '/images/sc/sc9.png',
    data_size: 's',
    title: 'web.dev',
    author: ['Andy Bell', 'Chrome Developer Team'],
  },
  {
    id: 10,
    img: '/images/sc/sc10.png',
    data_size: 'l',
    title: 'Leading Design',
    author: ['Clearleft'],
  },
  {
    id: 11,
    img: '/images/sc/sc11.png',
    data_size: 'l',
    title: 'Suffolk Libraries',
    author: ['Clearleft'],
  },
  {
    id: 12,
    img: '/images/sc/sc12.png',
    data_size: 's',
    title: 'Wildlife Photographer of the Year',
    author: ['Clearleft', 'NHM'],
  },
  {
    id: 13,
    img: '/images/sc/sc13.png',
    data_size: 's',
    title: 'CKEditor',
    author: ['CKSource'],
  },
  {
    id: 14,
    img: '/images/sc/sc14.png',
    data_size: 'l',
    title: 'BRYCK',
    author: ['9elements'],
  },
  {
    id: 15,
    img: '/images/sc/sc15.png',
    data_size: 'l',
    title: 'Trys Mudford',
    author: ['Trys Mudford'],
  },
  {
    id: 16,
    img: '/images/sc/sc16.png',
    data_size: 's',
    title: 'Enhance',
    author: ['Cole Peters'],
  },
  {
    id: 17,
    img: '/images/sc/sc17.png',
    data_size: 's',
    title: 'Cassie Evans',
    author: ['Cassie Evans'],
  },
  {
    id: 18,
    img: '/images/sc/sc18.png',
    data_size: 'l',
    title: 'Sofaconf',
    author: ['Clearleft'],
  },
];
